"""Add forum extension models

Revision ID: 0b79d8cbf540
Revises: 6e18d3a8cb28
Create Date: 2026-03-09 19:27:25.299605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b79d8cbf540'
down_revision = '6e18d3a8cb28'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
