"""Add forum models

Revision ID: 449f6e29e8d1
Revises: 5047d8c73856
Create Date: 2026-03-09 17:43:16.493434

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449f6e29e8d1'
down_revision = '5047d8c73856'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
