"""Add forum extension models

Revision ID: 6e18d3a8cb28
Revises: 52c37c5c9071
Create Date: 2026-03-09 19:27:05.619514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e18d3a8cb28'
down_revision = '52c37c5c9071'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
