"""add_cms_module_phase6

Revision ID: 705f093f3c7f
Revises: f1e2d3c4b5a6
Create Date: 2026-04-26 20:19:57.446483

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '705f093f3c7f'
down_revision = 'f1e2d3c4b5a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cms_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_categories_id'), 'cms_categories', ['id'], unique=False)
    op.create_index(op.f('ix_cms_categories_name'), 'cms_categories', ['name'], unique=True)
    op.create_index(op.f('ix_cms_categories_slug'), 'cms_categories', ['slug'], unique=True)
    op.create_table('cms_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_tags_id'), 'cms_tags', ['id'], unique=False)
    op.create_index(op.f('ix_cms_tags_name'), 'cms_tags', ['name'], unique=True)
    op.create_index(op.f('ix_cms_tags_slug'), 'cms_tags', ['slug'], unique=True)
    op.create_table('cms_media',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('mime', sa.String(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_media_created_at'), 'cms_media', ['created_at'], unique=False)
    op.create_index(op.f('ix_cms_media_created_by'), 'cms_media', ['created_by'], unique=False)
    op.create_index(op.f('ix_cms_media_id'), 'cms_media', ['id'], unique=False)
    op.create_table('cms_pages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.Enum('MARKDOWN', name='cmscontentformat'), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('meta_title', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='cmsstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_pages_created_at'), 'cms_pages', ['created_at'], unique=False)
    op.create_index(op.f('ix_cms_pages_created_by'), 'cms_pages', ['created_by'], unique=False)
    op.create_index(op.f('ix_cms_pages_id'), 'cms_pages', ['id'], unique=False)
    op.create_index(op.f('ix_cms_pages_published_at'), 'cms_pages', ['published_at'], unique=False)
    op.create_index(op.f('ix_cms_pages_slug'), 'cms_pages', ['slug'], unique=True)
    op.create_index(op.f('ix_cms_pages_status'), 'cms_pages', ['status'], unique=False)
    op.create_index(op.f('ix_cms_pages_updated_at'), 'cms_pages', ['updated_at'], unique=False)
    op.create_table('cms_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_format', sa.Enum('MARKDOWN', name='cmscontentformat'), nullable=False),
    sa.Column('excerpt', sa.Text(), nullable=True),
    sa.Column('cover_image_url', sa.String(), nullable=True),
    sa.Column('meta_title', sa.String(), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'ARCHIVED', name='cmsstatus'), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['cms_categories.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_posts_category_id'), 'cms_posts', ['category_id'], unique=False)
    op.create_index(op.f('ix_cms_posts_created_at'), 'cms_posts', ['created_at'], unique=False)
    op.create_index(op.f('ix_cms_posts_created_by'), 'cms_posts', ['created_by'], unique=False)
    op.create_index(op.f('ix_cms_posts_id'), 'cms_posts', ['id'], unique=False)
    op.create_index(op.f('ix_cms_posts_published_at'), 'cms_posts', ['published_at'], unique=False)
    op.create_index(op.f('ix_cms_posts_slug'), 'cms_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_cms_posts_status'), 'cms_posts', ['status'], unique=False)
    op.create_index(op.f('ix_cms_posts_updated_at'), 'cms_posts', ['updated_at'], unique=False)
    op.create_table('cms_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.Enum('PAGE', 'POST', name='cmsrevisionentitytype'), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cms_revisions_created_at'), 'cms_revisions', ['created_at'], unique=False)
    op.create_index(op.f('ix_cms_revisions_created_by'), 'cms_revisions', ['created_by'], unique=False)
    op.create_index(op.f('ix_cms_revisions_entity_id'), 'cms_revisions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_cms_revisions_entity_type'), 'cms_revisions', ['entity_type'], unique=False)
    op.create_index(op.f('ix_cms_revisions_id'), 'cms_revisions', ['id'], unique=False)
    op.create_table('cms_post_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['cms_posts.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['cms_tags.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('post_id', 'tag_id', name='uq_cms_post_tag')
    )
    op.create_index(op.f('ix_cms_post_tags_id'), 'cms_post_tags', ['id'], unique=False)
    op.create_index(op.f('ix_cms_post_tags_post_id'), 'cms_post_tags', ['post_id'], unique=False)
    op.create_index(op.f('ix_cms_post_tags_tag_id'), 'cms_post_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cms_post_tags_tag_id'), table_name='cms_post_tags')
    op.drop_index(op.f('ix_cms_post_tags_post_id'), table_name='cms_post_tags')
    op.drop_index(op.f('ix_cms_post_tags_id'), table_name='cms_post_tags')
    op.drop_table('cms_post_tags')
    op.drop_index(op.f('ix_cms_revisions_id'), table_name='cms_revisions')
    op.drop_index(op.f('ix_cms_revisions_entity_type'), table_name='cms_revisions')
    op.drop_index(op.f('ix_cms_revisions_entity_id'), table_name='cms_revisions')
    op.drop_index(op.f('ix_cms_revisions_created_by'), table_name='cms_revisions')
    op.drop_index(op.f('ix_cms_revisions_created_at'), table_name='cms_revisions')
    op.drop_table('cms_revisions')
    op.drop_index(op.f('ix_cms_posts_updated_at'), table_name='cms_posts')
    op.drop_index(op.f('ix_cms_posts_status'), table_name='cms_posts')
    op.drop_index(op.f('ix_cms_posts_slug'), table_name='cms_posts')
    op.drop_index(op.f('ix_cms_posts_published_at'), table_name='cms_posts')
    op.drop_index(op.f('ix_cms_posts_id'), table_name='cms_posts')
    op.drop_index(op.f('ix_cms_posts_created_by'), table_name='cms_posts')
    op.drop_index(op.f('ix_cms_posts_created_at'), table_name='cms_posts')
    op.drop_index(op.f('ix_cms_posts_category_id'), table_name='cms_posts')
    op.drop_table('cms_posts')
    op.drop_index(op.f('ix_cms_pages_updated_at'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_status'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_slug'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_published_at'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_id'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_created_by'), table_name='cms_pages')
    op.drop_index(op.f('ix_cms_pages_created_at'), table_name='cms_pages')
    op.drop_table('cms_pages')
    op.drop_index(op.f('ix_cms_media_id'), table_name='cms_media')
    op.drop_index(op.f('ix_cms_media_created_by'), table_name='cms_media')
    op.drop_index(op.f('ix_cms_media_created_at'), table_name='cms_media')
    op.drop_table('cms_media')
    op.drop_index(op.f('ix_cms_tags_slug'), table_name='cms_tags')
    op.drop_index(op.f('ix_cms_tags_name'), table_name='cms_tags')
    op.drop_index(op.f('ix_cms_tags_id'), table_name='cms_tags')
    op.drop_table('cms_tags')
    op.drop_index(op.f('ix_cms_categories_slug'), table_name='cms_categories')
    op.drop_index(op.f('ix_cms_categories_name'), table_name='cms_categories')
    op.drop_index(op.f('ix_cms_categories_id'), table_name='cms_categories')
    op.drop_table('cms_categories')
    op.execute("DROP TYPE IF EXISTS cmsrevisionentitytype")
    op.execute("DROP TYPE IF EXISTS cmsstatus")
    op.execute("DROP TYPE IF EXISTS cmscontentformat")
    # ### end Alembic commands ###
