"""Add admin models

Revision ID: 9d05601adb8a
Revises: a6f72b0d7aed
Create Date: 2026-03-09 16:28:48.227659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d05601adb8a'
down_revision = 'a6f72b0d7aed'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
