"""Initial migration

Revision ID: f15f07db59cc
Revises: f4da8d47eb37
Create Date: 2026-03-09 15:26:53.215467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f15f07db59cc'
down_revision = 'f4da8d47eb37'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
