name: Deploy YaConnect

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@master

        with:
          host: 75.119.157.125
          username: deploy
          key: ${{ secrets.VPS_SSH_PRIVATE_KEY }}

          script: |
            cd ~/apps/yaconnect
            git pull origin main
            docker compose down
            docker compose up -d --build